// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/user/user.proto

package user_service_user

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type User struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Password             string   `protobuf:"bytes,3,opt,name=password,proto3" json:"password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *User) Reset()         { *m = User{} }
func (m *User) String() string { return proto.CompactTextString(m) }
func (*User) ProtoMessage()    {}
func (*User) Descriptor() ([]byte, []int) {
	return fileDescriptor_9b283a848145d6b7, []int{0}
}

func (m *User) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_User.Unmarshal(m, b)
}
func (m *User) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_User.Marshal(b, m, deterministic)
}
func (m *User) XXX_Merge(src proto.Message) {
	xxx_messageInfo_User.Merge(m, src)
}
func (m *User) XXX_Size() int {
	return xxx_messageInfo_User.Size(m)
}
func (m *User) XXX_DiscardUnknown() {
	xxx_messageInfo_User.DiscardUnknown(m)
}

var xxx_messageInfo_User proto.InternalMessageInfo

func (m *User) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *User) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *User) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type CreateRequest struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Password             string   `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateRequest) Reset()         { *m = CreateRequest{} }
func (m *CreateRequest) String() string { return proto.CompactTextString(m) }
func (*CreateRequest) ProtoMessage()    {}
func (*CreateRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_9b283a848145d6b7, []int{1}
}

func (m *CreateRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateRequest.Unmarshal(m, b)
}
func (m *CreateRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateRequest.Marshal(b, m, deterministic)
}
func (m *CreateRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateRequest.Merge(m, src)
}
func (m *CreateRequest) XXX_Size() int {
	return xxx_messageInfo_CreateRequest.Size(m)
}
func (m *CreateRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateRequest proto.InternalMessageInfo

func (m *CreateRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *CreateRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type Request struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Password             string   `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Request) Reset()         { *m = Request{} }
func (m *Request) String() string { return proto.CompactTextString(m) }
func (*Request) ProtoMessage()    {}
func (*Request) Descriptor() ([]byte, []int) {
	return fileDescriptor_9b283a848145d6b7, []int{2}
}

func (m *Request) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Request.Unmarshal(m, b)
}
func (m *Request) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Request.Marshal(b, m, deterministic)
}
func (m *Request) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Request.Merge(m, src)
}
func (m *Request) XXX_Size() int {
	return xxx_messageInfo_Request.Size(m)
}
func (m *Request) XXX_DiscardUnknown() {
	xxx_messageInfo_Request.DiscardUnknown(m)
}

var xxx_messageInfo_Request proto.InternalMessageInfo

func (m *Request) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Request) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type Response struct {
	Code                 int64    `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message              string   `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	User                 *User    `protobuf:"bytes,3,opt,name=user,proto3" json:"user,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Response) Reset()         { *m = Response{} }
func (m *Response) String() string { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()    {}
func (*Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_9b283a848145d6b7, []int{3}
}

func (m *Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response.Unmarshal(m, b)
}
func (m *Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response.Marshal(b, m, deterministic)
}
func (m *Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response.Merge(m, src)
}
func (m *Response) XXX_Size() int {
	return xxx_messageInfo_Response.Size(m)
}
func (m *Response) XXX_DiscardUnknown() {
	xxx_messageInfo_Response.DiscardUnknown(m)
}

var xxx_messageInfo_Response proto.InternalMessageInfo

func (m *Response) GetCode() int64 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *Response) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *Response) GetUser() *User {
	if m != nil {
		return m.User
	}
	return nil
}

func init() {
	proto.RegisterType((*User)(nil), "user.service.user.user")
	proto.RegisterType((*CreateRequest)(nil), "user.service.user.CreateRequest")
	proto.RegisterType((*Request)(nil), "user.service.user.Request")
	proto.RegisterType((*Response)(nil), "user.service.user.Response")
}

func init() { proto.RegisterFile("proto/user/user.proto", fileDescriptor_9b283a848145d6b7) }

var fileDescriptor_9b283a848145d6b7 = []byte{
	// 241 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x51, 0xc1, 0x4a, 0x03, 0x31,
	0x10, 0x35, 0xd9, 0xa5, 0xad, 0x23, 0x0a, 0x0e, 0x88, 0x61, 0xbd, 0x2c, 0x7b, 0x2a, 0x08, 0x2b,
	0xd4, 0x93, 0x27, 0x05, 0x41, 0xf1, 0x1a, 0xf0, 0x03, 0x62, 0x33, 0xc8, 0x1e, 0xda, 0xac, 0x99,
	0x54, 0x3f, 0xc4, 0x1f, 0x96, 0x4c, 0xdd, 0x82, 0xba, 0x82, 0x78, 0x99, 0xcc, 0x0b, 0xef, 0x3d,
	0xf2, 0x5e, 0xe0, 0xa4, 0x8f, 0x21, 0x85, 0x8b, 0x0d, 0x53, 0x94, 0xd1, 0x0a, 0xc6, 0x63, 0xd9,
	0x99, 0xe2, 0x6b, 0xb7, 0xa4, 0x36, 0x83, 0xe6, 0x0e, 0xca, 0x7c, 0xe2, 0x11, 0xe8, 0xce, 0x1b,
	0x55, 0xab, 0x79, 0x61, 0x75, 0xe7, 0x11, 0xa1, 0x5c, 0xbb, 0x15, 0x19, 0x5d, 0xab, 0xf9, 0xbe,
	0x95, 0x1d, 0x2b, 0x98, 0xf5, 0x8e, 0xf9, 0x2d, 0x44, 0x6f, 0x0a, 0xb9, 0xdf, 0xe1, 0xe6, 0x1a,
	0x0e, 0x6f, 0x23, 0xb9, 0x44, 0x96, 0x5e, 0x36, 0xc4, 0x69, 0x67, 0xa0, 0x7e, 0x31, 0xd0, 0xdf,
	0x0c, 0xae, 0x60, 0xfa, 0x5f, 0x29, 0xc1, 0xcc, 0x12, 0xf7, 0x61, 0xcd, 0x94, 0xb5, 0xcb, 0xe0,
	0xe9, 0x33, 0x89, 0xec, 0x68, 0x60, 0xba, 0x22, 0x66, 0xf7, 0x3c, 0xc4, 0x19, 0x20, 0x9e, 0x6f,
	0xd3, 0x4b, 0x9a, 0x83, 0xc5, 0x69, 0xfb, 0xa3, 0x1f, 0x19, 0x56, 0x48, 0x8b, 0x77, 0x05, 0xe5,
	0x63, 0xee, 0xea, 0x01, 0x26, 0xdb, 0xac, 0x58, 0x8f, 0x28, 0xbe, 0xd4, 0x50, 0x9d, 0x8d, 0x30,
	0x86, 0xc7, 0x36, 0x7b, 0x78, 0x03, 0xc5, 0x3d, 0x25, 0xac, 0x46, 0x59, 0x7f, 0x71, 0x78, 0x9a,
	0xc8, 0xd7, 0x5e, 0x7e, 0x04, 0x00, 0x00, 0xff, 0xff, 0xd8, 0x13, 0x48, 0xed, 0xf3, 0x01, 0x00,
	0x00,
}
