apiVersion: v1
kind: Service
metadata:
  name: {{ template "prometheus-node-exporter.fullname" . }}
  namespace: {{ template "prometheus-node-exporter.namespace" . }}
{{- if .Values.handler.annotations }}
  annotations:
{{ toYaml .Values.handler.annotations | indent 4 }}
{{- end }}
  labels: {{ include "prometheus-node-exporter.labels" . | indent 4 }}
spec:
  type: {{ .Values.handler.type }}
  ports:
    - port: {{ .Values.handler.port }}
    {{- if ( and (eq .Values.handler.type "NodePort" ) (not (empty .Values.handler.nodePort)) ) }}
      nodePort: {{ .Values.handler.nodePort }}
    {{- end }}
      targetPort: {{ .Values.handler.targetPort }}
      protocol: TCP
      name: metrics
  selector:
    app: {{ template "prometheus-node-exporter.name" . }}
    release: {{ .Release.Name }}
