{{- if .Values.kubeEtcd.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ template "prometheus-operator.fullname" . }}-kube-etcd
  labels:
    app: {{ template "prometheus-operator.name" . }}-kube-etcd
    jobLabel: kube-etcd
{{ include "prometheus-operator.labels" . | indent 4 }}
  namespace: kube-system
spec:
  clusterIP: None
  ports:
    - name: http-metrics
      port: {{ .Values.kubeEtcd.handler.port }}
      protocol: TCP
      targetPort: {{ .Values.kubeEtcd.handler.targetPort }}
{{- if .Values.kubeEtcd.endpoints }}{{- else }}
  selector:
    {{- if .Values.kubeEtcd.handler.selector }}
{{ toYaml .Values.kubeEtcd.handler.selector | indent 4 }}
    {{- else}}
    component: etcd
    {{- end}}
{{- end }}
  type: ClusterIP
{{- end -}}
