{{- if .Values.prometheusOperator.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ template "prometheus-operator.fullname" . }}-operator
  namespace: {{ template "prometheus-operator.namespace" . }}
  labels:
    app: {{ template "prometheus-operator.name" . }}-operator
{{ include "prometheus-operator.labels" . | indent 4 }}
{{- if .Values.prometheusOperator.handler.labels }}
{{ toYaml .Values.prometheusOperator.handler.labels | indent 4 }}
{{- end }}
{{- if .Values.prometheusOperator.handler.annotations }}
  annotations:
{{ toYaml .Values.prometheusOperator.handler.annotations | indent 4 }}
{{- end }}
spec:
{{- if .Values.prometheusOperator.handler.clusterIP }}
  clusterIP: {{ .Values.prometheusOperator.handler.clusterIP }}
{{- end }}
{{- if .Values.prometheusOperator.handler.externalIPs }}
  externalIPs:
{{ toYaml .Values.prometheusOperator.handler.externalIPs | indent 4 }}
{{- end }}
{{- if .Values.prometheusOperator.handler.loadBalancerIP }}
  loadBalancerIP: {{ .Values.prometheusOperator.handler.loadBalancerIP }}
{{- end }}
{{- if .Values.prometheusOperator.handler.loadBalancerSourceRanges }}
  loadBalancerSourceRanges:
  {{- range $cidr := .Values.prometheusOperator.handler.loadBalancerSourceRanges }}
    - {{ $cidr }}
  {{- end }}
{{- end }}
  ports:
  - name: http
    {{- if eq .Values.prometheusOperator.handler.type "NodePort" }}
    nodePort: {{ .Values.prometheusOperator.handler.nodePort }}
    {{- end }}
    port: 8080
    targetPort: http
  {{- if .Values.prometheusOperator.tlsProxy.enabled }}
  - name: https
    {{- if eq .Values.prometheusOperator.handler.type "NodePort"}}
    nodePort: {{ .Values.prometheusOperator.handler.nodePortTls }}
    {{- end }}
    port: 443
    targetPort: https
  {{- end }}
  selector:
    app: {{ template "prometheus-operator.name" . }}-operator
    release: {{ $.Release.Name | quote }}
  type: "{{ .Values.prometheusOperator.handler.type }}"
{{- end }}
