apiVersion: v1
kind: Service
metadata:
  name: {{ template "grafana.fullname" . }}
  namespace: {{ template "grafana.namespace" . }}
  labels:
    {{- include "grafana.labels" . | nindent 4 }}
{{- if .Values.handler.labels }}
{{ toYaml .Values.handler.labels | indent 4 }}
{{- end }}
{{- with .Values.handler.annotations }}
  annotations:
{{ toYaml . | indent 4 }}
{{- end }}
spec:
{{- if (or (eq .Values.handler.type "ClusterIP") (empty .Values.handler.type)) }}
  type: ClusterIP
  {{- if .Values.handler.clusterIP }}
  clusterIP: {{ .Values.handler.clusterIP }}
  {{end}}
{{- else if eq .Values.handler.type "LoadBalancer" }}
  type: {{ .Values.handler.type }}
  {{- if .Values.handler.loadBalancerIP }}
  loadBalancerIP: {{ .Values.handler.loadBalancerIP }}
  {{- end }}
  {{- if .Values.handler.loadBalancerSourceRanges }}
  loadBalancerSourceRanges:
{{ toYaml .Values.handler.loadBalancerSourceRanges | indent 4 }}
  {{- end -}}
{{- else }}
  type: {{ .Values.handler.type }}
{{- end }}
{{- if .Values.handler.externalIPs }}
  externalIPs:
{{ toYaml .Values.handler.externalIPs | indent 4 }}
{{- end }}
  ports:
    - name: {{ .Values.handler.portName }}
      port: {{ .Values.handler.port }}
      protocol: TCP
      targetPort: {{ .Values.handler.targetPort }}
{{ if (and (eq .Values.handler.type "NodePort") (not (empty .Values.handler.nodePort))) }}
      nodePort: {{.Values.handler.nodePort}}
{{ end }}
  {{- if .Values.extraExposePorts }}
  {{- tpl (toYaml .Values.extraExposePorts) . | indent 4 }}
  {{- end }}
  selector:
    {{- include "grafana.selectorLabels" . | nindent 4 }}

