{{- if .Values.kubeScheduler.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ template "prometheus-operator.fullname" . }}-kube-scheduler
  labels:
    app: {{ template "prometheus-operator.name" . }}-kube-scheduler
    jobLabel: kube-scheduler
{{ include "prometheus-operator.labels" . | indent 4 }}
  namespace: kube-system
spec:
  clusterIP: None
  ports:
    - name: http-metrics
      port: {{ .Values.kubeScheduler.handler.port}}
      protocol: TCP
      targetPort: {{ .Values.kubeScheduler.handler.targetPort}}
{{- if .Values.kubeScheduler.endpoints }}{{- else }}
  selector:
    {{- if .Values.kubeScheduler.handler.selector }}
{{ toYaml .Values.kubeScheduler.handler.selector | indent 4 }}
    {{- else}}
    component: kube-scheduler
    {{- end}}
{{- end }}
  type: ClusterIP
{{- end -}}
