version: 2.1
jobs:
  build:
    docker:
      - image: circleci/golang:1.14.4
    working_directory: /go/release
    steps:
      - checkout
      - run:
          name: "检测有改动的微服务目录"
          command: |
            git diff --no-commit-id --name-only -r `git log -n 2 --oneline --pretty=format:"%h" | tail -n1` | cut -d/ -f1 | sort -u >  projects
            printf "Modified directories:\n"
            cat projects
            while read project; do
              if grep -Fxq $project ./.circleci/service-dirs; then
                printf "\nTriggerring build for project: "$project
                curl -s -u ${CIRCLE_TOKEN}: -d build_parameters[CIRCLE_JOB]=${project} https://circleci.com/api/v1.1/project/github/$CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME/tree/$CIRCLE_BRANCH
              fi
            done < projects
  user-service:
    docker:
      - image: circleci/golang:1.14.4
    environment:
      GO111MODULE: on
      GOPROXY: https://goproxy.cn,direct
    working_directory: /go/release/liaotian/user-service
    steps:
      - build-service:
          service_name: "user-service"
  user-web:
    docker:
      - image: circleci/golang:1.14.4
    environment:
      GO111MODULE: on
      GOPROXY: https://goproxy.cn,direct
    working_directory: /go/release/liaotian/user-web
    steps:
      - build-service:
          service_name: "user-web"

commands:
  build-service:
    description: "构建镜像并推送到阿里云"
    parameters:
      service_name:
        type: string
    steps:
      # git pull
      - checkout:
          path: ~/liaotian

      - setup_remote_docker:
          version: 19.03.12

      - run:
          name: "登录阿里云容器镜像服务"
          command: docker login --username=$DOCKER_USER $DOCKER_IMAGE_HOST -p $DOCKER_PASS

      # Download and cache dependencies
#      - restore_cache:
#          keys:
#            - << parameters.service_name >>-{{ checksum "pom.xml"}}

      - run:
          name: "从Dockerfile build镜像"
          command: docker build -t $DOCKER_IMAGE_HOST/$DOCKER_IMAGE_NAMESPACE/<< parameters.service_name >>:v${CIRCLE_BUILD_NUM} -f ~/liaotian/deploy/<< parameters.service_name >>/Dockerfile ~/liaotian/

#      - save_cache:
#          paths:
#            - ~/.m2
#          key: << parameters.service_name >>-{{ checksum "pom.xml"}}

      # package into a jar and build image
      - run:
          name: "push镜像到阿里云 "
          command: docker push $DOCKER_IMAGE_HOST/$DOCKER_IMAGE_NAMESPACE/<< parameters.service_name >>:${CIRCLE_BUILD_NUM}

      # store raw content of src code
#      - store_artifacts:
#          path: target/classes
#          destination: liaotian-<< parameters.service_name >>



