version: 2.1
jobs:
  build:
    docker:
      - image: circleci/golang:1.14.4
    working_directory: /go/release
    steps:
      - checkout
      - run:
          name: "检测有改动的微服务目录"
          command: |
            git diff --no-commit-id --name-only -r `git log -n 2 --oneline --pretty=format:"%h" | tail -n1` | cut -d/ -f2 | sort -u >  projects
            printf "Modified directories:\n"
            cat projects
            while read project; do
              if grep -Fxq $project ./.circleci/service-dirs; then
                printf "\nTriggerring build for project: "$project
                curl -s -u ${CIRCLE_TOKEN}: -d build_parameters[CIRCLE_JOB]=${project} https://circleci.com/api/v1.1/project/github/$CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME/tree/$CIRCLE_BRANCH
              fi
            done < projects
  user-service:
    docker:
      - image: circleci/golang:1.14.4
    environment:
      GO111MODULE: on
      GOPROXY: https://goproxy.cn,direct
    working_directory: /go/release/liaotian/user-handler
    steps:
      - build-service:
          service_name: "user-handler"
  user-web:
    docker:
      - image: circleci/golang:1.14.4
    environment:
      GO111MODULE: on
      GOPROXY: https://goproxy.cn,direct
    working_directory: /go/release/liaotian/user-web
    steps:
      - build-service:
          service_name: "user-web"
  domain-user:
    docker:
      - image: circleci/golang:1.14.4
    environment:
      GO111MODULE: on
      GOPROXY: https://goproxy.cn,direct
    working_directory: /go/release/liaotian/domain/user
    steps:
      - build-service:
          service_name: "domain-user"
  app-im:
    docker:
      - image: circleci/golang:1.14.4
    environment:
      GO111MODULE: on
      GOPROXY: https://goproxy.cn,direct
    working_directory: /go/release/liaotian/app/im
    steps:
      - build-service:
          service_name: "app-im"

commands:
  build-service:
    description: "构建镜像并推送到阿里云"
    parameters:
      service_name:
        type: string
    steps:
      # git pull
      - checkout:
          path: ~/liaotian

      - setup_remote_docker:
          version: 19.03.12

      - run:
          name: "登录阿里云容器镜像服务"
          command: docker login --username=$DOCKER_USER $DOCKER_IMAGE_HOST -p $DOCKER_PASS

      - run:
          name: "从Dockerfile build镜像"
          command: docker build -t $DOCKER_IMAGE_HOST/$DOCKER_IMAGE_NAMESPACE/<< parameters.service_name >>:latest -f ~/liaotian/.circleci/<< parameters.service_name >>/Dockerfile ~/liaotian/

      # package into a jar and build image
      - run:
          name: "push镜像到阿里云 "
          command: docker push $DOCKER_IMAGE_HOST/$DOCKER_IMAGE_NAMESPACE/<< parameters.service_name >>:latest



