// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: proto/auth.proto

package proto

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

import (
	context "context"
	client "github.com/micro/go-micro/client"
	server "github.com/micro/go-micro/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ client.Option
var _ server.Option

// Client API for Auth service

type AuthService interface {
	Generated(ctx context.Context, in *GeneratedRequest, opts ...client.CallOption) (*GeneratedResponse, error)
	Parse(ctx context.Context, in *ParseRequest, opts ...client.CallOption) (*ParseResponse, error)
}

type authService struct {
	c    client.Client
	name string
}

func NewAuthService(name string, c client.Client) AuthService {
	if c == nil {
		c = client.NewClient()
	}
	if len(name) == 0 {
		name = "domain.auth.service"
	}
	return &authService{
		c:    c,
		name: name,
	}
}

func (c *authService) Generated(ctx context.Context, in *GeneratedRequest, opts ...client.CallOption) (*GeneratedResponse, error) {
	req := c.c.NewRequest(c.name, "Auth.Generated", in)
	out := new(GeneratedResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authService) Parse(ctx context.Context, in *ParseRequest, opts ...client.CallOption) (*ParseResponse, error) {
	req := c.c.NewRequest(c.name, "Auth.Parse", in)
	out := new(ParseResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Auth service

type AuthHandler interface {
	Generated(context.Context, *GeneratedRequest, *GeneratedResponse) error
	Parse(context.Context, *ParseRequest, *ParseResponse) error
}

func RegisterAuthHandler(s server.Server, hdlr AuthHandler, opts ...server.HandlerOption) error {
	type auth interface {
		Generated(ctx context.Context, in *GeneratedRequest, out *GeneratedResponse) error
		Parse(ctx context.Context, in *ParseRequest, out *ParseResponse) error
	}
	type Auth struct {
		auth
	}
	h := &authHandler{hdlr}
	return s.Handle(s.NewHandler(&Auth{h}, opts...))
}

type authHandler struct {
	AuthHandler
}

func (h *authHandler) Generated(ctx context.Context, in *GeneratedRequest, out *GeneratedResponse) error {
	return h.AuthHandler.Generated(ctx, in, out)
}

func (h *authHandler) Parse(ctx context.Context, in *ParseRequest, out *ParseResponse) error {
	return h.AuthHandler.Parse(ctx, in, out)
}
