apiVersion: v1
kind: ConfigMap
metadata:
  name: user-service-cm
  namespace: liaotian
data:
  mysql_url: url=debian-sys-maint:F0sm3f7WrNJox1oV@tcp(129.211.55.205:3306)/liaotian
  skywalking_url: url=oap.skywalking:11800
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service
  namespace: liaotian
spec:
  replicas: 2
  selector:
    matchLabels:
      app: user-service
  template:
    metadata:
      labels:
        app: user-service
    spec:
      containers:
        - name: user-service
          image: test:v1
          imagePullPolicy: Never
          ports:
            - name: 80-port
              containerPort: 80
      nodeSelector:
        disktype: master
      serviceAccountName: liaotian-account  # serviceAccount的名称 用于权限
---
apiVersion: v1
kind: Service
metadata:
  name: user-service
  namespace: liaotian
spec:
  ports:
    - name: 80-port
      port: 80
      targetPort: 80
  selector:
    app: user-service