apiVersion: v1
kind: Service
metadata:
  name: {{ template "kube-state-metrics.fullname" . }}
  namespace: {{ template "kube-state-metrics.namespace" . }}
  labels:
    app.kubernetes.io/name: {{ template "kube-state-metrics.name" . }}
    helm.sh/chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    app.kubernetes.io/instance: "{{ .Release.Name }}"
    app.kubernetes.io/managed-by: "{{ .Release.Service }}"
{{- if .Values.customLabels }}
{{ toYaml .Values.customLabels | indent 4 }}
{{- end }}
  annotations:
    {{- if .Values.prometheusScrape }}
    prometheus.io/scrape: '{{ .Values.prometheusScrape }}'
    {{- end }}
    {{- if .Values.handler.annotations }}
    {{- toYaml .Values.handler.annotations | nindent 4 }}
    {{- end }}
spec:
  type: "{{ .Values.handler.type }}"
  ports:
  - name: "http"
    protocol: TCP
    port: {{ .Values.handler.port }}
  {{- if .Values.handler.nodePort }}
    nodePort: {{ .Values.handler.nodePort }}
  {{- end }}
    targetPort: 8080
{{- if .Values.handler.loadBalancerIP }}
  loadBalancerIP: "{{ .Values.handler.loadBalancerIP }}"
{{- end }}
  selector:
    app.kubernetes.io/name: {{ template "kube-state-metrics.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
