apiVersion: v1
kind: PersistentVolume
metadata:
  labels:
    {{- include "prometheus.server.labels" . | nindent 4 }}
  name: {{ template "prometheus.server.fullname" . }}
{{ include "prometheus.namespace" . | indent 2 }}
spec:
  capacity:
    storage: "{{ .Values.server.persistentVolume.size }}"
  accessModes:
{{ toYaml .Values.server.persistentVolume.accessModes | indent 4 }}
  hostPath:
    path: "/tmp/data/prometheus"