apiVersion: nats.io/v1alpha2
kind: NatsCluster
metadata:
  name: nats-cluster
  namespace: nats
spec:
  size: 3
  version: "2.1.8"
  pod:
    enableClientsHostPort: true
#    advertiseExternalIP: true

  template:
    spec:
      serviceAccountName: "nats-server"