// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: proto/user.proto

package proto

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

import (
	context "context"
	client "github.com/micro/go-micro/client"
	server "github.com/micro/go-micro/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ client.Option
var _ server.Option

// Client API for User service

type UserService interface {
	CreateUserInfo(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error)
	GetUserInfo(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error)
	UpdateUserInfo(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error)
	CheckUserPwd(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error)
	BatchGetUserInfo(ctx context.Context, in *BatchGetUserInfoRequest, opts ...client.CallOption) (*BatchGetUserInfoResponse, error)
}

type userService struct {
	c    client.Client
	name string
}

func NewUserService(name string, c client.Client) UserService {
	if c == nil {
		c = client.NewClient()
	}
	if len(name) == 0 {
		name = "domain.user.service"
	}
	return &userService{
		c:    c,
		name: name,
	}
}

func (c *userService) CreateUserInfo(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error) {
	req := c.c.NewRequest(c.name, "User.CreateUserInfo", in)
	out := new(Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userService) GetUserInfo(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error) {
	req := c.c.NewRequest(c.name, "User.GetUserInfo", in)
	out := new(Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userService) UpdateUserInfo(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error) {
	req := c.c.NewRequest(c.name, "User.UpdateUserInfo", in)
	out := new(Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userService) CheckUserPwd(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error) {
	req := c.c.NewRequest(c.name, "User.CheckUserPwd", in)
	out := new(Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userService) BatchGetUserInfo(ctx context.Context, in *BatchGetUserInfoRequest, opts ...client.CallOption) (*BatchGetUserInfoResponse, error) {
	req := c.c.NewRequest(c.name, "User.BatchGetUserInfo", in)
	out := new(BatchGetUserInfoResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for User service

type UserHandler interface {
	CreateUserInfo(context.Context, *Request, *Response) error
	GetUserInfo(context.Context, *Request, *Response) error
	UpdateUserInfo(context.Context, *Request, *Response) error
	CheckUserPwd(context.Context, *Request, *Response) error
	BatchGetUserInfo(context.Context, *BatchGetUserInfoRequest, *BatchGetUserInfoResponse) error
}

func RegisterUserHandler(s server.Server, hdlr UserHandler, opts ...server.HandlerOption) error {
	type user interface {
		CreateUserInfo(ctx context.Context, in *Request, out *Response) error
		GetUserInfo(ctx context.Context, in *Request, out *Response) error
		UpdateUserInfo(ctx context.Context, in *Request, out *Response) error
		CheckUserPwd(ctx context.Context, in *Request, out *Response) error
		BatchGetUserInfo(ctx context.Context, in *BatchGetUserInfoRequest, out *BatchGetUserInfoResponse) error
	}
	type User struct {
		user
	}
	h := &userHandler{hdlr}
	return s.Handle(s.NewHandler(&User{h}, opts...))
}

type userHandler struct {
	UserHandler
}

func (h *userHandler) CreateUserInfo(ctx context.Context, in *Request, out *Response) error {
	return h.UserHandler.CreateUserInfo(ctx, in, out)
}

func (h *userHandler) GetUserInfo(ctx context.Context, in *Request, out *Response) error {
	return h.UserHandler.GetUserInfo(ctx, in, out)
}

func (h *userHandler) UpdateUserInfo(ctx context.Context, in *Request, out *Response) error {
	return h.UserHandler.UpdateUserInfo(ctx, in, out)
}

func (h *userHandler) CheckUserPwd(ctx context.Context, in *Request, out *Response) error {
	return h.UserHandler.CheckUserPwd(ctx, in, out)
}

func (h *userHandler) BatchGetUserInfo(ctx context.Context, in *BatchGetUserInfoRequest, out *BatchGetUserInfoResponse) error {
	return h.UserHandler.BatchGetUserInfo(ctx, in, out)
}
