version: '3'

services:
  zookeeper:
    image: 'wurstmeister/zookeeper'
    restart: always
    ports:
      - "2181:2181"
  kafka:
    image: "wurstmeister/kafka"
    volumes:
      - /etc/localtime:/etc/localtime
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 192.168.66.104
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_PORT: 9092
  kafka-manager:
    image: "sheepkiller/kafka-manager"
    environment:
      ZK_HOSTS: 192.168.66.104
    ports:
      - "9001:9000"
