apiVersion: apps/v1
kind: Deployment
metadata:
  name: friend-web
  namespace: liaotian
spec:
  replicas: 2
  selector:
    matchLabels:
      app: friend-web
  template:
    metadata:
      labels:
        app: friend-web
    spec:
      containers:
        - name: friend-web
          image: liaotian/friend-web:v1.0
          imagePullPolicy: Never
          ports:
            - name: 80-port
              containerPort: 80
          env:
            - name: SERVICE_PORT
              value: ":80"
      serviceAccountName: liaotian-account  # serviceAccount的名称 用于权限
---
apiVersion: v1
kind: Service
metadata:
  name: friend-web
  namespace: liaotian
spec:
  ports:
    - name: 80-port
      port: 80
      targetPort: 80
  selector:
    app: friend-web