{{- if .Values.alertmanager.enabled -}}
apiVersion: v1
kind: Service
metadata:
{{- if .Values.alertmanager.handler.annotations }}
  annotations:
{{ toYaml .Values.alertmanager.handler.annotations | indent 4 }}
{{- end }}
  labels:
    {{- include "prometheus.alertmanager.labels" . | nindent 4 }}
{{- if .Values.alertmanager.handler.labels }}
{{ toYaml .Values.alertmanager.handler.labels | indent 4 }}
{{- end }}
  name: {{ template "prometheus.alertmanager.fullname" . }}
{{ include "prometheus.namespace" . | indent 2 }}
spec:
{{- if .Values.alertmanager.handler.clusterIP }}
  clusterIP: {{ .Values.alertmanager.handler.clusterIP }}
{{- end }}
{{- if .Values.alertmanager.handler.externalIPs }}
  externalIPs:
{{ toYaml .Values.alertmanager.handler.externalIPs | indent 4 }}
{{- end }}
{{- if .Values.alertmanager.handler.loadBalancerIP }}
  loadBalancerIP: {{ .Values.alertmanager.handler.loadBalancerIP }}
{{- end }}
{{- if .Values.alertmanager.handler.loadBalancerSourceRanges }}
  loadBalancerSourceRanges:
  {{- range $cidr := .Values.alertmanager.handler.loadBalancerSourceRanges }}
    - {{ $cidr }}
  {{- end }}
{{- end }}
  ports:
    - name: http
      port: {{ .Values.alertmanager.handler.servicePort }}
      protocol: TCP
      targetPort: 9093
    {{- if .Values.alertmanager.handler.nodePort }}
      nodePort: {{ .Values.alertmanager.handler.nodePort }}
    {{- end }}
{{- if .Values.alertmanager.handler.enableMeshPeer }}
    - name: meshpeer
      port: 6783
      protocol: TCP
      targetPort: 6783
{{- end }}
  selector:
    {{- include "prometheus.alertmanager.matchLabels" . | nindent 4 }}
{{- if .Values.alertmanager.handler.sessionAffinity }}
  sessionAffinity: {{ .Values.alertmanager.handler.sessionAffinity }}
{{- end }}
  type: "{{ .Values.alertmanager.handler.type }}"
{{- end }}
