{{- if .Values.pushgateway.enabled -}}
apiVersion: v1
kind: Service
metadata:
{{- if .Values.pushgateway.handler.annotations }}
  annotations:
{{ toYaml .Values.pushgateway.handler.annotations | indent 4}}
{{- end }}
  labels:
    {{- include "prometheus.pushgateway.labels" . | nindent 4 }}
{{- if .Values.pushgateway.handler.labels }}
{{ toYaml .Values.pushgateway.handler.labels | indent 4}}
{{- end }}
  name: {{ template "prometheus.pushgateway.fullname" . }}
{{ include "prometheus.namespace" . | indent 2 }}
spec:
{{- if .Values.pushgateway.handler.clusterIP }}
  clusterIP: {{ .Values.pushgateway.handler.clusterIP }}
{{- end }}
{{- if .Values.pushgateway.handler.externalIPs }}
  externalIPs:
{{ toYaml .Values.pushgateway.handler.externalIPs | indent 4 }}
{{- end }}
{{- if .Values.pushgateway.handler.loadBalancerIP }}
  loadBalancerIP: {{ .Values.pushgateway.handler.loadBalancerIP }}
{{- end }}
{{- if .Values.pushgateway.handler.loadBalancerSourceRanges }}
  loadBalancerSourceRanges:
  {{- range $cidr := .Values.pushgateway.handler.loadBalancerSourceRanges }}
    - {{ $cidr }}
  {{- end }}
{{- end }}
  ports:
    - name: http
      port: {{ .Values.pushgateway.handler.servicePort }}
      protocol: TCP
      targetPort: 9091
  selector:
    {{- include "prometheus.pushgateway.matchLabels" . | nindent 4 }}
  type: "{{ .Values.pushgateway.handler.type }}"
{{- end }}
