{{- if .Values.server.enabled -}}
apiVersion: v1
kind: Service
metadata:
{{- if .Values.server.handler.annotations }}
  annotations:
{{ toYaml .Values.server.handler.annotations | indent 4 }}
{{- end }}
  labels:
    {{- include "prometheus.server.labels" . | nindent 4 }}
{{- if .Values.server.handler.labels }}
{{ toYaml .Values.server.handler.labels | indent 4 }}
{{- end }}
  name: {{ template "prometheus.server.fullname" . }}
{{ include "prometheus.namespace" . | indent 2 }}
spec:
{{- if .Values.server.handler.clusterIP }}
  clusterIP: {{ .Values.server.handler.clusterIP }}
{{- end }}
{{- if .Values.server.handler.externalIPs }}
  externalIPs:
{{ toYaml .Values.server.handler.externalIPs | indent 4 }}
{{- end }}
{{- if .Values.server.handler.loadBalancerIP }}
  loadBalancerIP: {{ .Values.server.handler.loadBalancerIP }}
{{- end }}
{{- if .Values.server.handler.loadBalancerSourceRanges }}
  loadBalancerSourceRanges:
  {{- range $cidr := .Values.server.handler.loadBalancerSourceRanges }}
    - {{ $cidr }}
  {{- end }}
{{- end }}
  ports:
    - name: http
      port: {{ .Values.server.handler.servicePort }}
      protocol: TCP
      targetPort: 9090
    {{- if .Values.server.handler.nodePort }}
      nodePort: {{ .Values.server.handler.nodePort }}
    {{- end }}
    {{- if .Values.server.handler.gRPC.enabled }}
    - name: grpc
      port: {{ .Values.server.handler.gRPC.servicePort }}
      protocol: TCP
      targetPort: 10901
    {{- if .Values.server.handler.gRPC.nodePort }}
      nodePort: {{ .Values.server.handler.gRPC.nodePort }}
    {{- end }}
    {{- end }}
  selector:
  {{- if and .Values.server.statefulSet.enabled .Values.server.handler.statefulsetReplica.enabled }}
    statefulset.kubernetes.io/pod-name: {{ template "prometheus.server.fullname" . }}-{{ .Values.server.handler.statefulsetReplica.replica }}
  {{- else -}}
    {{- include "prometheus.server.matchLabels" . | nindent 4 }}
{{- if .Values.server.handler.sessionAffinity }}
  sessionAffinity: {{ .Values.server.handler.sessionAffinity }}
{{- end }}
  {{- end }}
  type: "{{ .Values.server.handler.type }}"
{{- end -}}
