// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: proto/friend/friend.proto

package friend_service_friend

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

import (
	context "context"
	client "github.com/micro/go-micro/client"
	server "github.com/micro/go-micro/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ client.Option
var _ server.Option

// Client API for Friend service

type FriendService interface {
	Add(ctx context.Context, in *AddRequest, opts ...client.CallOption) (*Response, error)
	Del(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error)
	List(ctx context.Context, in *ListRequest, opts ...client.CallOption) (*Response, error)
	Get(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error)
}

type friendService struct {
	c    client.Client
	name string
}

func NewFriendService(name string, c client.Client) FriendService {
	if c == nil {
		c = client.NewClient()
	}
	if len(name) == 0 {
		name = "friend.service.friend"
	}
	return &friendService{
		c:    c,
		name: name,
	}
}

func (c *friendService) Add(ctx context.Context, in *AddRequest, opts ...client.CallOption) (*Response, error) {
	req := c.c.NewRequest(c.name, "Friend.Add", in)
	out := new(Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *friendService) Del(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error) {
	req := c.c.NewRequest(c.name, "Friend.Del", in)
	out := new(Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *friendService) List(ctx context.Context, in *ListRequest, opts ...client.CallOption) (*Response, error) {
	req := c.c.NewRequest(c.name, "Friend.List", in)
	out := new(Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *friendService) Get(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error) {
	req := c.c.NewRequest(c.name, "Friend.Get", in)
	out := new(Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Friend service

type FriendHandler interface {
	Add(context.Context, *AddRequest, *Response) error
	Del(context.Context, *Request, *Response) error
	List(context.Context, *ListRequest, *Response) error
	Get(context.Context, *Request, *Response) error
}

func RegisterFriendHandler(s server.Server, hdlr FriendHandler, opts ...server.HandlerOption) error {
	type friend interface {
		Add(ctx context.Context, in *AddRequest, out *Response) error
		Del(ctx context.Context, in *Request, out *Response) error
		List(ctx context.Context, in *ListRequest, out *Response) error
		Get(ctx context.Context, in *Request, out *Response) error
	}
	type Friend struct {
		friend
	}
	h := &friendHandler{hdlr}
	return s.Handle(s.NewHandler(&Friend{h}, opts...))
}

type friendHandler struct {
	FriendHandler
}

func (h *friendHandler) Add(ctx context.Context, in *AddRequest, out *Response) error {
	return h.FriendHandler.Add(ctx, in, out)
}

func (h *friendHandler) Del(ctx context.Context, in *Request, out *Response) error {
	return h.FriendHandler.Del(ctx, in, out)
}

func (h *friendHandler) List(ctx context.Context, in *ListRequest, out *Response) error {
	return h.FriendHandler.List(ctx, in, out)
}

func (h *friendHandler) Get(ctx context.Context, in *Request, out *Response) error {
	return h.FriendHandler.Get(ctx, in, out)
}
