// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/friend/friend.proto

package friend_service_friend

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Friend struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId               int64    `protobuf:"varint,2,opt,name=userId,proto3" json:"userId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Friend) Reset()         { *m = Friend{} }
func (m *Friend) String() string { return proto.CompactTextString(m) }
func (*Friend) ProtoMessage()    {}
func (*Friend) Descriptor() ([]byte, []int) {
	return fileDescriptor_f54247b80b303e7a, []int{0}
}

func (m *Friend) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Friend.Unmarshal(m, b)
}
func (m *Friend) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Friend.Marshal(b, m, deterministic)
}
func (m *Friend) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Friend.Merge(m, src)
}
func (m *Friend) XXX_Size() int {
	return xxx_messageInfo_Friend.Size(m)
}
func (m *Friend) XXX_DiscardUnknown() {
	xxx_messageInfo_Friend.DiscardUnknown(m)
}

var xxx_messageInfo_Friend proto.InternalMessageInfo

func (m *Friend) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Friend) GetUserId() int64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

type Request struct {
	FriendId             int64    `protobuf:"varint,1,opt,name=friendId,proto3" json:"friendId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Request) Reset()         { *m = Request{} }
func (m *Request) String() string { return proto.CompactTextString(m) }
func (*Request) ProtoMessage()    {}
func (*Request) Descriptor() ([]byte, []int) {
	return fileDescriptor_f54247b80b303e7a, []int{1}
}

func (m *Request) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Request.Unmarshal(m, b)
}
func (m *Request) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Request.Marshal(b, m, deterministic)
}
func (m *Request) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Request.Merge(m, src)
}
func (m *Request) XXX_Size() int {
	return xxx_messageInfo_Request.Size(m)
}
func (m *Request) XXX_DiscardUnknown() {
	xxx_messageInfo_Request.DiscardUnknown(m)
}

var xxx_messageInfo_Request proto.InternalMessageInfo

func (m *Request) GetFriendId() int64 {
	if m != nil {
		return m.FriendId
	}
	return 0
}

type Response struct {
	Code                 int64     `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message              string    `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Friend               *Friend   `protobuf:"bytes,3,opt,name=friend,proto3" json:"friend,omitempty"`
	List                 []*Friend `protobuf:"bytes,4,rep,name=list,proto3" json:"list,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *Response) Reset()         { *m = Response{} }
func (m *Response) String() string { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()    {}
func (*Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_f54247b80b303e7a, []int{2}
}

func (m *Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response.Unmarshal(m, b)
}
func (m *Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response.Marshal(b, m, deterministic)
}
func (m *Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response.Merge(m, src)
}
func (m *Response) XXX_Size() int {
	return xxx_messageInfo_Response.Size(m)
}
func (m *Response) XXX_DiscardUnknown() {
	xxx_messageInfo_Response.DiscardUnknown(m)
}

var xxx_messageInfo_Response proto.InternalMessageInfo

func (m *Response) GetCode() int64 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *Response) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *Response) GetFriend() *Friend {
	if m != nil {
		return m.Friend
	}
	return nil
}

func (m *Response) GetList() []*Friend {
	if m != nil {
		return m.List
	}
	return nil
}

type AddRequest struct {
	OperatorId           int64    `protobuf:"varint,1,opt,name=operatorId,proto3" json:"operatorId,omitempty"`
	BuddyId              int64    `protobuf:"varint,2,opt,name=buddyId,proto3" json:"buddyId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddRequest) Reset()         { *m = AddRequest{} }
func (m *AddRequest) String() string { return proto.CompactTextString(m) }
func (*AddRequest) ProtoMessage()    {}
func (*AddRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_f54247b80b303e7a, []int{3}
}

func (m *AddRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddRequest.Unmarshal(m, b)
}
func (m *AddRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddRequest.Marshal(b, m, deterministic)
}
func (m *AddRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddRequest.Merge(m, src)
}
func (m *AddRequest) XXX_Size() int {
	return xxx_messageInfo_AddRequest.Size(m)
}
func (m *AddRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AddRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AddRequest proto.InternalMessageInfo

func (m *AddRequest) GetOperatorId() int64 {
	if m != nil {
		return m.OperatorId
	}
	return 0
}

func (m *AddRequest) GetBuddyId() int64 {
	if m != nil {
		return m.BuddyId
	}
	return 0
}

type ListRequest struct {
	OperatorId           int64    `protobuf:"varint,1,opt,name=operatorId,proto3" json:"operatorId,omitempty"`
	Offset               int64    `protobuf:"varint,2,opt,name=offset,proto3" json:"offset,omitempty"`
	Limit                int64    `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListRequest) Reset()         { *m = ListRequest{} }
func (m *ListRequest) String() string { return proto.CompactTextString(m) }
func (*ListRequest) ProtoMessage()    {}
func (*ListRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_f54247b80b303e7a, []int{4}
}

func (m *ListRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListRequest.Unmarshal(m, b)
}
func (m *ListRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListRequest.Marshal(b, m, deterministic)
}
func (m *ListRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListRequest.Merge(m, src)
}
func (m *ListRequest) XXX_Size() int {
	return xxx_messageInfo_ListRequest.Size(m)
}
func (m *ListRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListRequest proto.InternalMessageInfo

func (m *ListRequest) GetOperatorId() int64 {
	if m != nil {
		return m.OperatorId
	}
	return 0
}

func (m *ListRequest) GetOffset() int64 {
	if m != nil {
		return m.Offset
	}
	return 0
}

func (m *ListRequest) GetLimit() int64 {
	if m != nil {
		return m.Limit
	}
	return 0
}

func init() {
	proto.RegisterType((*Friend)(nil), "friend.service.friend.friend")
	proto.RegisterType((*Request)(nil), "friend.service.friend.Request")
	proto.RegisterType((*Response)(nil), "friend.service.friend.Response")
	proto.RegisterType((*AddRequest)(nil), "friend.service.friend.AddRequest")
	proto.RegisterType((*ListRequest)(nil), "friend.service.friend.ListRequest")
}

func init() { proto.RegisterFile("proto/friend/friend.proto", fileDescriptor_f54247b80b303e7a) }

var fileDescriptor_f54247b80b303e7a = []byte{
	// 321 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x92, 0xcf, 0x4e, 0x02, 0x31,
	0x10, 0xc6, 0xdd, 0x3f, 0x2e, 0x38, 0x24, 0x1e, 0x26, 0x4a, 0x56, 0x12, 0x11, 0x9b, 0x98, 0x70,
	0x42, 0xc5, 0xf8, 0x00, 0x24, 0x06, 0x25, 0xea, 0xa5, 0x57, 0x4f, 0x40, 0x07, 0xd3, 0x04, 0x28,
	0xb6, 0xc5, 0xc4, 0xd7, 0xf1, 0x29, 0x7c, 0x3c, 0x43, 0xbb, 0x45, 0x0e, 0x6e, 0xdc, 0x83, 0xa7,
	0xf6, 0x9b, 0x7c, 0x33, 0xfb, 0xfd, 0x66, 0x0b, 0x27, 0x2b, 0xad, 0xac, 0xba, 0x9c, 0x69, 0x49,
	0x4b, 0x51, 0x1c, 0x3d, 0x57, 0xc3, 0xe3, 0x42, 0x19, 0xd2, 0xef, 0x72, 0x4a, 0x3d, 0x2f, 0xd9,
	0x15, 0x64, 0xfe, 0x86, 0x87, 0x10, 0x4b, 0x91, 0x47, 0x9d, 0xa8, 0x9b, 0xf0, 0x58, 0x0a, 0x6c,
	0x42, 0xb6, 0x36, 0xa4, 0x47, 0x22, 0x8f, 0x5d, 0xad, 0x50, 0xec, 0x02, 0x6a, 0x9c, 0xde, 0xd6,
	0x64, 0x2c, 0xb6, 0xa0, 0xee, 0x9b, 0x47, 0xa1, 0x71, 0xab, 0xd9, 0x67, 0x04, 0x75, 0x4e, 0x66,
	0xa5, 0x96, 0x86, 0x10, 0x21, 0x9d, 0x2a, 0x41, 0x85, 0xc9, 0xdd, 0x31, 0x87, 0xda, 0x82, 0x8c,
	0x19, 0xbf, 0x92, 0xfb, 0xc0, 0x01, 0x0f, 0x12, 0x6f, 0x43, 0xa6, 0x3c, 0xe9, 0x44, 0xdd, 0x46,
	0xff, 0xb4, 0xf7, 0x6b, 0xf6, 0xe2, 0xe0, 0x01, 0xe0, 0x1a, 0xd2, 0xb9, 0x34, 0x36, 0x4f, 0x3b,
	0xc9, 0xdf, 0x4d, 0xce, 0xca, 0x86, 0x00, 0x03, 0x21, 0x02, 0x4e, 0x1b, 0x40, 0xad, 0x48, 0x8f,
	0xad, 0xd2, 0x5b, 0xa0, 0x9d, 0xca, 0x26, 0xf1, 0x64, 0x2d, 0xc4, 0xc7, 0x76, 0x25, 0x41, 0xb2,
	0x17, 0x68, 0x3c, 0x49, 0x63, 0xab, 0x0e, 0x6a, 0x42, 0xa6, 0x66, 0x33, 0x43, 0x36, 0xac, 0xd6,
	0x2b, 0x3c, 0x82, 0xfd, 0xb9, 0x5c, 0x48, 0xeb, 0xb8, 0x13, 0xee, 0x45, 0xff, 0x2b, 0x86, 0x6c,
	0xe8, 0x11, 0x1f, 0x21, 0x19, 0x08, 0x81, 0xe7, 0x25, 0x6c, 0x3f, 0x2c, 0xad, 0xb3, 0x12, 0x4b,
	0xf8, 0x25, 0x6c, 0x0f, 0x1f, 0x20, 0xb9, 0xa3, 0x39, 0xb6, 0x4b, 0x9d, 0x95, 0x27, 0x3d, 0x43,
	0xba, 0xc1, 0x47, 0x56, 0x62, 0xdd, 0xd9, 0x4d, 0xc5, 0x60, 0xf7, 0x64, 0xff, 0x21, 0xd8, 0x24,
	0x73, 0x6f, 0xff, 0xe6, 0x3b, 0x00, 0x00, 0xff, 0xff, 0x76, 0x01, 0xb5, 0x73, 0x18, 0x03, 0x00,
	0x00,
}
