apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-web
  namespace: liaotian
spec:
  replicas: 3
  selector:
    matchLabels:
      app: user-web
  template:
    metadata:
      labels:
        app: user-web
    spec:
      containers:
        - name: user-web
          image: registry.cn-hangzhou.aliyuncs.com/liaotian_csh/user-web:latest
          imagePullPolicy: Always
          ports:
            - name: 80-port
              containerPort: 80
          env:
            - name: SERVICE_PORT
              value: ":80"
      serviceAccountName: liaotian-account  # serviceAccount的名称 用于权限
---
apiVersion: v1
kind: Service
metadata:
  name: user-web
  namespace: liaotian
spec:
  ports:
    - name: 80-port
      port: 80
      targetPort: 80
  selector:
    app: user-web