{{- if .Values.kubeDns.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ template "prometheus-operator.fullname" . }}-kube-dns
  labels:
    app: {{ template "prometheus-operator.name" . }}-kube-dns
    jobLabel: kube-dns
{{ include "prometheus-operator.labels" . | indent 4 }}
  namespace: kube-system
spec:
  clusterIP: None
  ports:
    - name: http-metrics-dnsmasq
      port: {{ .Values.kubeDns.handler.dnsmasq.port }}
      protocol: TCP
      targetPort: {{ .Values.kubeDns.handler.dnsmasq.targetPort }}
    - name: http-metrics-skydns
      port: {{ .Values.kubeDns.handler.skydns.port }}
      protocol: TCP
      targetPort: {{ .Values.kubeDns.handler.skydns.targetPort }}
  selector:
    {{- if .Values.kubeDns.handler.selector }}
{{ toYaml .Values.kubeDns.handler.selector | indent 4 }}
    {{- else}}
    k8s-app: kube-dns
    {{- end}}
{{- end }}
